baseurl = "/"
title = "Code & Beer"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Red teamer & Beer taster"
    description = "It's rainning..."
    github = "https://github.com/leinn32"
    twitter = "https://twitter.com/leinn32"
    email = "leinn32@sideralsynchrony.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"

